#!/bin/bash

# Setup GitHub Actions Secrets
# Este script guia você para configurar os secrets necessários para sync automático

echo "🔐 CONFIGURAÇÃO DE GITHUB ACTIONS SECRETS"
echo "========================================="
echo ""
echo "Para habilitar sync automático 100% funcional, você precisa"
echo "configurar 5 secrets no repositório GitHub."
echo ""
echo "📋 SECRETS NECESSÁRIOS:"
echo ""
echo "1. NEXT_PUBLIC_CARTPANDA_API_URL"
echo "   Valor: https://accounts.cartpanda.com/api/v3"
echo ""
echo "2. CARTPANDA_API_TOKEN"
echo "   Valor: 4QypzWuXZ8LRFlDI1InfE5c0oHvGz9ws6T4AMnqEVEx7VUBkiCF8sDP2j28e"
echo ""
echo "3. CARTPANDA_STORE_NAME"
echo "   Valor: beliuimcaps"
echo ""
echo "4. NEXT_PUBLIC_SUPABASE_URL"
echo "   Valor: https://swogockrnapyymcuorgs.supabase.co"
echo ""
echo "5. NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "   Valor: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3b2dvY2tybmFweXltY3VvcmdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDc1NjAsImV4cCI6MjA2MjYyMzU2MH0._Fo8MF9WTLiCPu112YZLJzszH1rGE3mimX_AaLFHeHQ"
echo ""
echo "========================================="
echo ""
echo "📖 COMO CONFIGURAR (PASSO A PASSO):"
echo ""
echo "OPÇÃO 1: Via Interface Web (Mais Fácil)"
echo "----------------------------------------"
echo "1. Acesse: https://github.com/SEU_USUARIO/dashboard/settings/secrets/actions"
echo "2. Clique em 'New repository secret'"
echo "3. Adicione cada secret acima (nome + valor)"
echo "4. Clique em 'Add secret'"
echo "5. Repita para os 5 secrets"
echo ""
echo "OPÇÃO 2: Via GitHub CLI (Mais Rápido)"
echo "----------------------------------------"
echo "Se você tem GitHub CLI instalado:"
echo ""
echo "  gh secret set NEXT_PUBLIC_CARTPANDA_API_URL -b'https://accounts.cartpanda.com/api/v3'"
echo "  gh secret set CARTPANDA_API_TOKEN -b'4QypzWuXZ8LRFlDI1InfE5c0oHvGz9ws6T4AMnqEVEx7VUBkiCF8sDP2j28e'"
echo "  gh secret set CARTPANDA_STORE_NAME -b'beliuimcaps'"
echo "  gh secret set NEXT_PUBLIC_SUPABASE_URL -b'https://swogockrnapyymcuorgs.supabase.co'"
echo "  gh secret set NEXT_PUBLIC_SUPABASE_ANON_KEY -b'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3b2dvY2tybmFweXltY3VvcmdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDc1NjAsImV4cCI6MjA2MjYyMzU2MH0._Fo8MF9WTLiCPu112YZLJzszH1rGE3mimX_AaLFHeHQ'"
echo ""
echo "========================================="
echo ""
echo "✅ VERIFICAÇÃO"
echo ""
echo "Após configurar os secrets:"
echo ""
echo "1. Acesse: https://github.com/SEU_USUARIO/dashboard/actions"
echo "2. Selecione 'Hourly Incremental Sync'"
echo "3. Clique em 'Run workflow' → 'Run workflow'"
echo "4. Aguarde ~2-5 minutos"
echo "5. Verifique se executou com sucesso (check verde)"
echo ""
echo "Se executar com sucesso, o sync automático está FUNCIONANDO!"
echo ""
echo "========================================="
echo ""
echo "📅 QUANDO VAI RODAR AUTOMATICAMENTE:"
echo ""
echo "Sync Incremental (4x por dia):"
echo "  - 00:00 UTC (21:00 Brasília) ✅"
echo "  - 06:00 UTC (03:00 Brasília) ✅"
echo "  - 12:00 UTC (09:00 Brasília) ✅"
echo "  - 18:00 UTC (15:00 Brasília) ✅"
echo ""
echo "Validação Diária (1x por dia):"
echo "  - 09:00 UTC (06:00 Brasília) ✅"
echo ""
echo "========================================="
echo ""
echo "❓ PRECISA DE AJUDA?"
echo ""
echo "Documentação GitHub Secrets:"
echo "https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions"
echo ""
echo "Ou execute manualmente:"
echo "  npm run sync:full"
echo ""

# Verificar se GitHub CLI está instalado
if command -v gh &> /dev/null; then
    echo ""
    echo "🎉 GitHub CLI detectado!"
    echo ""
    read -p "Deseja configurar os secrets agora via GitHub CLI? (s/n): " -n 1 -r
    echo ""

    if [[ $REPLY =~ ^[Ss]$ ]]; then
        echo "Configurando secrets..."
        echo ""

        gh secret set NEXT_PUBLIC_CARTPANDA_API_URL -b'https://accounts.cartpanda.com/api/v3' && echo "✅ NEXT_PUBLIC_CARTPANDA_API_URL configurado"
        gh secret set CARTPANDA_API_TOKEN -b'4QypzWuXZ8LRFlDI1InfE5c0oHvGz9ws6T4AMnqEVEx7VUBkiCF8sDP2j28e' && echo "✅ CARTPANDA_API_TOKEN configurado"
        gh secret set CARTPANDA_STORE_NAME -b'beliuimcaps' && echo "✅ CARTPANDA_STORE_NAME configurado"
        gh secret set NEXT_PUBLIC_SUPABASE_URL -b'https://swogockrnapyymcuorgs.supabase.co' && echo "✅ NEXT_PUBLIC_SUPABASE_URL configurado"
        gh secret set NEXT_PUBLIC_SUPABASE_ANON_KEY -b'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3b2dvY2tybmFweXltY3VvcmdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDc1NjAsImV4cCI6MjA2MjYyMzU2MH0._Fo8MF9WTLiCPu112YZLJzszH1rGE3mimX_AaLFHeHQ' && echo "✅ NEXT_PUBLIC_SUPABASE_ANON_KEY configurado"

        echo ""
        echo "🎉 Secrets configurados com sucesso!"
        echo ""
        echo "Agora teste executando manualmente:"
        echo "  gh workflow run hourly-sync.yml"
        echo ""
        echo "Ou acesse: https://github.com/$(gh repo view --json nameWithOwner -q .nameWithOwner)/actions"
    else
        echo "Ok! Configure manualmente via interface web."
    fi
fi

echo ""
echo "========================================="
echo "Configuração concluída! 🚀"
echo "========================================="
